MLOPS-54 | Use volume for the inter-steps data
getindata/kedro-kubeflow pull request #9
Opened 2021-01-06 09:25 UTC by szczeles

2021-01-06 10:35 UTC, szczeles commented
@em-pe I decided to use `run_config` directly in the client class (instead of reading it in 4 functions in `plugin.py` and passing as params), maybe we can do same for other args: image, pull policy, etc. It would simplify the code - and anyway  - all these are required for most of the client functions.

2021-01-06 17:05 UTC, em-pe requested changes
@szczeles First of all well done with the volume support - that will solve a lot of hustle we had with adjusting projects to run on kubeflow.

Regarding using config file instead of parameters, in general I'm all in for it, but keep in mind in some scenarios you want to populate those fields with environment variables taken from CI job. That's the case for image definitely, but you'd like to use commit ID for a run name as well for example, we should support that. I wonder if `TemplatedConfigLoader` support env variables, because this would allow us to merry the two ideas. 

I don't have any complaints about a PR contents but please add an entry into CHANGELOG.md according to https://keepachangelog.com/en/1.0.0/ guidelines and incorporate example kubeflow.yml config file into README.md

I'll prepare MR template that would remind us to keep CHANGELOG.md up to date.

2021-01-07 08:18 UTC, szczeles commented
@em-pe Done, please recheck

2021-01-07 08:19 UTC, em-pe approved these changes

2021-01-07 08:25 UTC, merged